version: "3.8"

services:
  greenroom-localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - EXTRA_CORS_ALLOWED_ORIGIN=https://localhost:4200
      - AWS_ACCESS_KEY_ID=test_key
      - AWS_SECRET_ACCESS_KEY=test_secret
      - DEFAULT_REGION=us-east-1
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_S3=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  greenroom-sql-server:
      container_name: "greenroom-sql-server"
      image: "mcr.microsoft.com/azure-sql-edge"
      environment:
        MSSQL_SA_PASSWORD: "reallyStrongPwd123"
        ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"