version: 0.2
phases:
  dotnet-sdk-install:
    commands:
      - echo "Installing .NET SDK"
      - version=$(jq -r '.sdk.version' global.json)
      - if [ ! -d "$HOME/.dotnet/$version" ]; then
        wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh;
        chmod +x dotnet-install.sh;
        ./dotnet-install.sh --version $version --install-dir $HOME/.dotnet/$version;
        fi
      - export PATH=$HOME/.dotnet/$version:$PATH
  restore-dependencies:
    commands:
      - echo "Restoring solution"
      - dotnet restore GreenRoom.sln
  api-build:
    commands:
      - echo "Building solution"
      - dotnet build GreenRoom.sln
  api-test:
    commands:
      - echo "Testing solution"
      - dotnet test GreenRoom.sln --no-build --configuration Release --filter "FullyQualifiedName!~AcceptanceTests"
  api-publish:
    commands:
      - echo "Publishing website"
      - dotnet publish GreenRoom.sln --configuration Release --output ./publish
