version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo Installing .NET Core
      - dotnet --version

  pre_build:
    commands:
      - echo Restoring NuGet packages
      - dotnet restore

  build:
    commands:
      - echo Building the solution
      - dotnet build --no-restore --configuration Release
      - echo Running tests
      - dotnet test --no-build --configuration Release || exit 1

  post_build:
    commands:
      - echo Publishing website
      - cd src/Web
      - dotnet publish --configuration Release --output ./publish
      # - cd publish
      # - zip -r ./publish.zip .

artifacts:
  files:
    - src/Web/publish/**/*
    - appspec.yml
    - .aws/deployment-scripts/**/*
    - README.md
