name: Deploy

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: self-hosted
    environment: ${{ inputs.environmentName }}
    env:
      SQLAdminUsername: ${{ vars.AWS_SQL_ADMINISTRATOR_USERNAME }}
      SQLAdminPassword: ${{ secrets.AWS_SQL_ADMINISTRATOR_PASSWORD }}
      EnvironmentName: ${{ inputs.environmentName }}
      ProjectName: ${{ vars.PROJECT_NAME }} # to be set if not available
      AWS_REGION: ${{ vars.AWS_REGION }} # to be set if not available
      AWS_STACK_NAME: ${{ vars.AWS_STACK_NAME }} # to be set if not available

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - if: inputs.environmentName == 'Development'
        name: Run preflight validation
        run: |
          aws cloudformation validate-template --template-body file://./.aws/cloudformation/main.yaml

      - if: inputs.environmentName != 'Development'
        name: Run change set
        run: |
          aws cloudformation create-change-set --stack-name ${{ vars.AWS_STACK_NAME }} --template-body file://./.aws/cloudformation/main.yaml --change-set-name changeset-$(date +%s) --parameters ParameterKey=EnvironmentName,ParameterValue=${{ inputs.environmentName }} ParameterKey=SqlAdministratorUsername,ParameterValue=${{ vars.AWS_SQL_ADMINISTRATOR_USERNAME }} ParameterKey=SqlAdministratorPassword,ParameterValue=${{ secrets.AWS_SQL_ADMINISTRATOR_PASSWORD }} ParameterKey=ProjectName,ParameterValue=${{ vars.PROJECT_NAME }}

  deploy:
    needs: [validate]
    runs-on: self-hosted
    environment: ${{ inputs.environmentName }}

    steps:
      - name: Print environment variables and inputs
        run: |
          echo "SQLAdminUsername: ${{ vars.AWS_SQL_ADMINISTRATOR_USERNAME }}"
          echo "SQLAdminPassword: ${{ secrets.AWS_SQL_ADMINISTRATOR_PASSWORD }}"
          echo "EnvironmentName: ${{ inputs.environmentName }}"
          echo "ProjectName: ${{ vars.PROJECT_NAME }}"
          echo "AWS_REGION: ${{ vars.AWS_REGION }}"
          echo "AWS_STACK_NAME: ${{ vars.AWS_STACK_NAME }}"
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_REGION: ${{ vars.AWS_REGION }}"
          echo "AWS_STACK_NAME: ${{ vars.AWS_STACK_NAME }}"
          echo "AWS_RESOURCE_NAME_SUFFIX: ${{ vars.AWS_RESOURCE_NAME_SUFFIX }}"

      - uses: actions/checkout@v4
        name: Checkout code

      - uses: actions/download-artifact@v4
        name: Download artifacts

      - name: Install .NET
        uses: actions/setup-dotnet@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # - name: Deploy infrastructure
      #   run: |
      #     aws cloudformation deploy --stack-name ${{ vars.AWS_STACK_NAME }} --template-file ./.aws/cloudformation/main.yaml --parameter-overrides EnvironmentName=${{ inputs.environmentName }} SQLAdminUsername=${{ vars.AWS_SQL_ADMINISTRATOR_USERNAME }} SQLAdminPassword=${{ secrets.AWS_SQL_ADMINISTRATOR_PASSWORD }} ProjectName=${{ vars.PROJECT_NAME }} ResourceNameSuffix=${{ vars.AWS_RESOURCE_NAME_SUFFIX }} KeyName=${{ vars.AWS_EC2_SSH_KEY_NAME }}

      - name: Create database if not exists
        run: |
          aws rds describe-db-instances --db-instance-identifier ${{ vars.AWS_RDS_SQLSERVER_DB_NAME }} || \
          aws rds create-db-instance --db-instance-identifier ${{ vars.AWS_RDS_SQLSERVER_DB_NAME }} --db-instance-class db.t2.micro --engine sqlserver-ex --master-username ${{ vars.AWS_SQL_ADMINISTRATOR_USERNAME }} --master-user-password ${{ secrets.AWS_SQL_ADMINISTRATOR_PASSWORD }} --allocated-storage 20

      - name: Deploy database migration
        run: |
          unzip -o ./efbundle/efbundle.zip
          echo '{ "ConnectionStrings": { "DefaultConnection": "" } }' > appsettings.json
          ./efbundle.exe --connection "Server=${{ vars.AWS_SQL_SERVER_ENDPOINT }};Initial Catalog=${{ vars.AWS_RDS_SQLSERVER_DB_NAME }};Persist Security Info=False;User ID=${{ vars.AWS_SQL_ADMINISTRATOR_USERNAME }};Password=${{ secrets.AWS_SQL_ADMINISTRATOR_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" --migrate --verbose

      - name: Deploy .NET WebAPI to EC2
        run: |
          aws ec2 describe-instances --filters "Name=tag:Name,Values=${{ vars.EC2_INSTANCE_NAME }}" --query "Reservations[*].Instances[*].InstanceId" --output text > instance_id.txt
          INSTANCE_ID=$(cat instance_id.txt)
          aws ssm send-command --instance-ids $INSTANCE_ID --document-name "AWS-RunShellScript" --comment "Deploy .NET WebAPI" --parameters commands="cd /var/www/${{ vars.PROJECT_NAME }} && git pull && dotnet publish -c Release -o out && sudo systemctl restart kestrel-${{ vars.PROJECT_NAME }}.service"

      - name: Notify deployment success
        run: echo "Deployment to ${{ inputs.environmentName }} environment was successful!"
